
services:
  app: 
    image: de4et/command-constructor
    container_name: cc-backend
    ports:
      - "80:5000"
      - "443:443"
    depends_on:
      - mongodb
    volumes:
      - /certs:/certs
    environment:
      - SSL_CERT_PATH=/certs/certificate.crt
      - SSL_KEY_PATH=/certs/certificate.key

  mongodb:
    image: mongo:8.0
    container_name: cc-mdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: command-constructor
    volumes:
      - mongodbdata:/var/lib/mongodb

volumes:
  mongodbdata:
    external: true