
services:
  app: 
    image: command-constructor
    container_name: cc-backend
    ports:
      - "80:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0
    container_name: cc-mdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: command-constructor
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: