// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LogOnto() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"log_menu\"><div class=\"login_block\"><button id=\"login_button\" class=\"log_button\">Вход</button><div id=\"login_content\" class=\"login_content\"><form class=\"login_form\" id=\"login_form\" method=\"post\" action=\"/api/auth\"><input name=\"name\" class=\"log_input\" placeholder=\"Логин\"> <input name=\"password\" type=\"password\" class=\"log_input\" placeholder=\"Пароль\"> <button type=\"submit\" class=\"log_submit_button\">Войти</button><div hidden=\"true\" class=\"lds-ellipsis loading-animation\"><div></div><div></div><div></div><div></div></div></form></div></div><div class=\"reg_block\"><button id=\"reg_button\" class=\"log_button\">Регистрация</button><div id=\"reg_content\" class=\"login_content\"><form class=\"login_form\" id=\"reg_form\" method=\"post\" action=\"/api/reg\"><input name=\"name\" class=\"log_input\" placeholder=\"Логин\"> <input name=\"email\" class=\"log_input\" placeholder=\"Email\"> <input name=\"password\" type=\"password\" class=\"log_input\" placeholder=\"Пароль\"> <button type=\"submit\" class=\"log_submit_button\">Зарегистрироваться</button><div hidden=\"true\" class=\"lds-ellipsis loading-animation\"><div></div><div></div><div></div><div></div></div></form></div></div><script>\r\n\t\t\taddOpenableBlockListeners(\".login_block\", \"#login_button\", \"#login_content\");\r\n\t\t\taddOpenableBlockListeners(\".reg_block\", \"#reg_button\", \"#reg_content\");\r\n\t\t</script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
